### ISSUE TITLE
fix link to mybinder

### ISSUE THREAD

**Issue by lunebellec** [PSY3018/cours2_principes_irm#2]
currently the link does not point to the main repo

**Comment by sangfrois** [comment]
once it is ready to merge, i will make a last commit with the change. Otherwise, we wouldn't be able to test the current version of the notebook. It is tracking my fork/branch

**Comment by lunebellec** [comment]
Your changes are already merged in the main repo.

**Comment by lunebellec** [comment]
fixed.
